version: '3.9'

services:
  crypto-converter-master:
    image: aroman35/banana-crypto-converter:${VERSION_TAG}
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: "http://*:8080"
      DOTNET_ENVIRONMENT: "Production"
    ports:
      - "6950:8080"
    networks:
      - svc-network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 20s
    configs:
      - source: crypto-converter.master.appsettings.json
        target: /bin/appsettings.json

  crypto-converter-workers:
    image: aroman35/banana-crypto-converter:${VERSION_TAG}
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      ASPNETCORE_URLS: "http://*:8080"
      DOTNET_ENVIRONMENT: "Production"
    volumes:
      - market-data-storage:/market-data-storage
    networks:
      - svc-network
    deploy:
      mode: replicated
      replicas: 8
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 2G
    configs:
      - source: crypto-converter.replica.appsettings.json
        target: /bin/appsettings.json

volumes:
  market-data-storage:
    driver_opts:
      type: cifs
      o: 'username=${NAS_USER},password=${NAS_PASSWORD},uid=${UID},gid-${GID} 0 0'
      device: ${NAS_PATH}

configs:
  crypto-converter.master.appsettings.json:
    file: ./crypto-converter.master.appsettings.json
    external: true
  crypto-converter.replica.appsettings.json:
    file: ./crypto-converter.replica.appsettings.json
    external: true

networks:
  svc-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.15.74.0/24
