version: "3.8"

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    hostname: redis-master
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6379",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--masterauth",
        "${REDIS_PASSWORD}",
        "--protected-mode",
        "no"
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.3

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    hostname: redis-slave-1
    restart: unless-stopped
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - redis-slave-1-data:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replicaof",
        "redis-master",
        "6379",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6380",
        "--masterauth",
        "${REDIS_PASSWORD}",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--protected-mode",
        "no"
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.4

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    hostname: redis-slave-2
    restart: unless-stopped
    depends_on:
      - redis-master
    ports:
      - "6381:6379"
    volumes:
      - redis-slave-2-data:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--replicaof",
        "redis-master",
        "6379",
        "--repl-diskless-load",
        "on-empty-db",
        "--replica-announce-ip",
        "${HOST_IP}",
        "--replica-announce-port",
        "6381",
        "--masterauth",
        "${REDIS_PASSWORD}",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--protected-mode",
        "no"
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.5

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    hostname: sentinel-1
    restart: unless-stopped
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor ${SERVICE_NAME} ${HOST_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds ${SERVICE_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout ${SERVICE_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs ${SERVICE_NAME} 1" >> /etc/sentinel.conf &&
            echo "sentinel auth-pass ${SERVICE_NAME} ${REDIS_PASSWORD}" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      redis-net:
        ipv4_address: 172.21.0.6

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    hostname: sentinel-2
    restart: unless-stopped
    depends_on:
      - redis-master
    ports:
      - "26380:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor ${SERVICE_NAME} ${HOST_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds ${SERVICE_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout ${SERVICE_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs ${SERVICE_NAME} 1" >> /etc/sentinel.conf &&
            echo "sentinel auth-pass ${SERVICE_NAME} ${REDIS_PASSWORD}" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      redis-net:
        ipv4_address: 172.21.0.7

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    hostname: sentinel-3
    restart: unless-stopped
    depends_on:
      - redis-master
    ports:
      - "26381:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor ${SERVICE_NAME} ${HOST_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds ${SERVICE_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout ${SERVICE_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs ${SERVICE_NAME} 1" >> /etc/sentinel.conf &&
            echo "sentinel auth-pass ${SERVICE_NAME} ${REDIS_PASSWORD}" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      redis-net:
        ipv4_address: 172.21.0.8

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      redis-net:
        ipv4_address: 172.21.0.9

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
volumes:
  redis-master-data:
    driver: local
  redis-slave-1-data:
    driver: local
  redis-slave-2-data:
    driver: local